#!/bin/bash
# suggested use for this:
# (1) Put in the id's for your robot, YOURROBOTID and YOURCAMERAID
# (2) use sudo to create a crontab entry: @reboot /bin/bash /home/pi/start_robot

cd /home/pi/runmyrobot
# to enable reverse ssh option to allow remote debugging by Let's Robot developers
nohup scripts/repeat_start python reverse_ssh.py YOURROBOTID &> /dev/null &

nohup scripts/repeat_start python controller.py YOURROBOTID &> /dev/null &
nohup scripts/repeat_start python send_video.py YOURCAMERAID 0 &> /dev/null &
